server:
  port: 8082

spring:
  application:
    name: analytics

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"